### PR TITLE
Fix asset pipeline flags

### LINKED ISSUE #4: flags.png is not fingerprinted
Tested on a Rails 4.2 app.

The intlTelInput.css file references the flags.png sprite which is not fingerprinted. When deploying on production using the asset pipeline, if the file has changed (as you recently updated it), you will probably get the older stale file, if you cache your assets in any way (eg. CDN).

Will try to send a fix soon.

### PR DESCRIPTION
**Pull request by teoulas**
This PR ensures that the flags sprite image goes through asset compilation and gets a fingerprinted filename.

Fixes #4

### CODE REVIEW

**Comment by ispyropoulos** [comment]
Does this create a dependency for the `sass-rails` gem?

**Comment by teoulas** [comment]
I guess so. I'm trying to find what other similar gems define as dependencies, but they're inconsistent. [X-editable-rails](https://github.com/werein/x-editable-rails/blob/master/x-editable-rails.gemspec) only specifies "railties", even though they use scss and its [image-url helper](https://github.com/werein/x-editable-rails/blob/master/vendor/assets/stylesheets/editable/bootstrap2-editable.scss#L51).

**Comment by ispyropoulos** [comment]
I guess is that most gem authors just neglect to specify what they need in production. They usually get away with it, because stuff are already there and nobody notices; especially when very common dependencies are involved. Let's be explicit and specify our dependency [here](https://github.com/ispyropoulos/intl-tel-input-rails/blob/6f99cf6fc97b048d2f823b4c241480c5d53aba86/intl-tel-input-rails.gemspec#L21). I think something like `spec.add_dependency "sass-rails"` will suffice.

**Comment by teoulas** [comment]
There you go

**Pull request merged**
